[package]
name = "sixteenbit"
version = "0.1.0"
edition = "2021"

[lib]
name = "sixteenbit_encoding"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4"
image = "0.24"
serde = "1.0"
bytemuck = "1.14"